title: Allen Firth
baseurl: /
permalink: '/:title/'
layout_style: overflow
palette: blue
header:
  bg: dark
  has_nav: true
  has_social: true
  profile_img: /images/profile.jpg
  tagline: SOFTWARE ARCHITECT & DEVELOPER
  title: ALLEN FIRTH
footer:
  content: '&copy; All rights reserved.'
  links:
    - new_window: true
      text: Made with Stackbit
      url: 'https://www.stackbit.com'
sass:
  indentWidth: 4
  precision: 10
  style: nested
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
